apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fr57
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fr57
    app.kubernetes.io/part-of: ci1t-830-0015-app
  name: devfile-sample-fr57
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fr57
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fr57
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0015-tenant/ci1t-830-0015-app/devfile-sample-fr57@sha256:6dc5a5a9705203e09e26cf41cbfb18db166485377f0f4ee76a7217ac54176712
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
